# Generated by Django 3.1.6 on 2021-05-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperpipeline', '0002_auto_20210508_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterposturls',
            name='origtext',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newsletterposturls',
            name='url',
            field=models.TextField(unique=True),
        ),
    ]
