# Generated by Django 3.1.6 on 2021-05-11 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraperpipeline', '0003_auto_20210510_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletterposturls',
            name='parentnewsletter',
        ),
    ]
