# Generated by Django 3.1.6 on 2021-05-11 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraperpipeline', '0004_remove_newsletterposturls_parentnewsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterposturls',
            name='parentnewsletter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraperpipeline.substacknewsletter'),
        ),
    ]
