# Generated by Django 3.1.6 on 2021-05-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperpipeline', '0005_newsletterposturls_parentnewsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='postsToIgnore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(unique=True)),
                ('countOfTriesSoFar', models.IntegerField(default=0)),
                ('errMsg', models.TextField(null=True)),
            ],
        ),
    ]
