# Generated by Django 3.1.6 on 2021-08-19 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraperpipeline', '0006_poststoignore'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('url', models.TextField(unique=True)),
                ('parentnewsletter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraperpipeline.substacknewsletter')),
            ],
        ),
    ]
